name: Release

on:
  push:
    branches:
    - 'prod'
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    name: Build and release
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Install dependencies
      if: worker.os == 'Linux'
      run: sudo apt-get install libgtk-3-dev
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build | Tests
      run: cargo test
    - name: Build | Linux | Add target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build | Linux | Production build with cargo
      if: runner.os == 'Linux'
      run: cargo build --target x86_64-unknown-linux-gnu --release
    - name: Build | Build with Cargo
      if: runner.os == 'Windows'
      run: cargo build --production
      
