name: Rust

on:
  push:
    branches:  
    - main
  pull_request:
    branches: 
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps: 
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build | Install dependencies
      run: cargo install
    - name: Build | Compile with Cargo
      run: cargo check
  test: 
    name: Test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build | Test with Cargo
      run: cargo test
  build:
    name: Build
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - name: Build | Build with Cargo
      run: cargo build
